FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /app
RUN apt-get update && apt-get install -y \
    libpq-dev gcc \
    && rm -rf /var/lib/apt/lists/*
COPY requirements-django.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements-django.txt
COPY . /app/
RUN python manage.py collectstatic --noinput
EXPOSE 8000
CMD ["gunicorn", "mindedhealth.wsgi:application", "--bind", "0.0.0.0:8000"]
