services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
    depends_on:
      - django

  redis:
    image: redis:7
    restart: unless-stopped

  django:
    image: kettyvaisbrot/mindedhealth-django:v7
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis

  ai-microservice:
    image: kettyvaisbrot/mindedhealth-ai:v31
    restart: unless-stopped
    env_file: .env

  insights-service:
    image: kettyvaisbrot/mindedhealth-insights:v1
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis

  celery-worker:
    image: kettyvaisbrot/mindedhealth-django:v7
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    command: celery -A MindedHealth worker --loglevel=info

  celery-beat:
    image: kettyvaisbrot/mindedhealth-django:v7
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    command: celery -A MindedHealth beat --loglevel=info

volumes:
  caddy_data:
