apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sqlite-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi  # Adjust the size according to your needs (1Gi = 1 GB)
  storageClassName: standard  # Make sure to use the right storage class available in your EKS cluster
