apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-master-0
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard   
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-redis-replicas-0
  namespace: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard   
