apiVersion: v1
kind: Service
metadata:
  name: mindedhealth-service
spec:
  selector:
    app: mindedhealth
  ports:
    - protocol: TCP
      port: 80  # External port for your app
      targetPort: 8000  # Internal port your app listens to
  type: LoadBalancer  # Use LoadBalancer for external access or ClusterIP for internal-only access
