"""
Django settings for MindedHealth project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
from datetime import timedelta
import os

load_dotenv()
BASE_DIR = Path(__file__).resolve().parent.parent
AUTH_USER_MODEL = "users.User"

# =======================
# STATIC FILES
# =======================
STATIC_ROOT = os.environ.get('STATIC_ROOT', os.path.join(BASE_DIR, 'staticfiles'))
STATIC_URL = "static/"

# =======================
# SECURITY SETTINGS
# =======================
DEBUG = os.getenv("DJANGO_DEBUG", "True").lower() in ["true", "1"]
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "*").split(",")
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
SECURE_SSL_REDIRECT = False

SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False

SECURE_HSTS_SECONDS = 0
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False

X_FRAME_OPTIONS = 'DENY'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = f"MindedHealth <{EMAIL_HOST_USER}>"

# =======================
# TIME ZONE & I18N
# =======================
TIME_ZONE = 'Asia/Jerusalem'
USE_TZ = True
USE_I18N = True
LANGUAGE_CODE = 'en-us'

# =======================
# ENV KEYS
# =======================
GOOGLE_SEARCH_API_KEY = os.getenv("GOOGLE_SEARCH_API_KEY")
GOOGLE_SEARCH_CSE_ID = os.getenv("GOOGLE_SEARCH_CSE_ID")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

# =======================
# APPLICATION DEFINITION
# =======================
INSTALLED_APPS = [
    "users",
    "insights",
    "drf_yasg",
    "rest_framework",
    "silk",
    "rest_framework.authtoken",
    "chatbot",
    "channels",
    "dashboard",
    "medications",
    "my_statistics",
    "what_interested_you",
    "dashboard.templatetags.custom_filters",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

REST_FRAMEWORK = {
    # Authentication
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    
    # Permissions
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated', 
    ],
    
    # Throttling to prevent abuse
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.UserRateThrottle',  
        'rest_framework.throttling.AnonRateThrottle',  
    ],
    'DEFAULT_THROTTLE_RATES': {
        'user': '1000/day',
        'anon': '100/day',    
    },

    # Pagination (avoid large responses)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 20, 

    # JSON-only responses (avoid content sniffing issues)
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),

    # Parsers (validate incoming content types)
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
}


# =======================
# JWT AUTHENTICATION
# =======================
#
# KEY MANAGEMENT STRATEGY
# -----------------------
# This project uses RS256 (asymmetric RSA signing).
# Django holds the private key and is the only service that can issue tokens.
# FastAPI services (insights_service, ai_microservice) and future workers
# hold only the public key and can verify tokens but never issue them.
#
# GENERATING KEYS (one-time per environment)
#   openssl genrsa -out private.pem 2048
#   openssl rsa -in private.pem -pubout -out public.pem
#
# Never commit either key file. Add *.pem to .gitignore.
#
# LOCAL DEVELOPMENT (.env)
#   Flatten the PEM to a single line by replacing real newlines with \n:
#   JWT_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n-----END RSA PRIVATE KEY-----"
#   JWT_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMIIB...\n-----END PUBLIC KEY-----"
#   settings.py converts \n back to real newlines via .replace('\\n', '\n').
#
# KUBERNETES (production)
#   Store as a Kubernetes Secret, never as a plain env var in the Deployment manifest:
#     kubectl create secret generic jwt-keys \
#       --from-literal=JWT_PRIVATE_KEY="$(cat private.pem)" \
#       --from-literal=JWT_PUBLIC_KEY="$(cat public.pem)"
#   Inject into pods via envFrom referencing the secret.
#   The private key secret must be scoped to the Django Deployment only.
#   The public key secret is shared with insights_service and ai_microservice Deployments.
#
# KEY ROTATION
#   1. Generate a new key pair.
#   2. Add the new public key to all verifying services alongside the old one
#      (both keys trusted simultaneously during the transition window).
#   3. Update Django to sign with the new private key.
#   4. Wait for all access tokens signed with the old key to expire (15 minutes).
#   5. Remove the old public key from verifying services.
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': False,
    'ALGORITHM': 'RS256',
    'SIGNING_KEY': os.getenv('JWT_PRIVATE_KEY', '').replace('\\n', '\n'),
    'VERIFYING_KEY': os.getenv('JWT_PUBLIC_KEY', '').replace('\\n', '\n'),
    'ISSUER': 'mindedhealth-auth',
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'sub',
    'JTI_CLAIM': 'jti',
    'TOKEN_OBTAIN_SERIALIZER': 'users.tokens.CustomTokenObtainPairSerializer',
}


# =======================
# INTERNAL SERVICE JWT
# =======================
# This key pair is SEPARATE from the user-facing JWT key pair above
# (SIMPLE_JWT / JWT_PRIVATE_KEY / JWT_PUBLIC_KEY).
#
# Django signs internal service tokens with INTERNAL_JWT_PRIVATE_KEY.
# Downstream FastAPI services (insights_service, ai_microservice) hold only
# INTERNAL_JWT_PUBLIC_KEY — never the private key and never the user JWT keys.
# User JWTs are validated once at the Django boundary and never forwarded.
#
# GENERATING KEYS (one-time per environment, separate from user JWT keys):
#   openssl genrsa -out internal_private.pem 2048
#   openssl rsa -in internal_private.pem -pubout -out internal_public.pem
#
# LOCAL DEVELOPMENT (.env) — same \n-escaping convention as JWT_PRIVATE_KEY:
#   INTERNAL_JWT_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIE...\n-----END RSA PRIVATE KEY-----"
#   INTERNAL_JWT_PUBLIC_KEY="-----BEGIN PUBLIC KEY-----\nMIIB...\n-----END PUBLIC KEY-----"
#
# KUBERNETES — store in a Secret named internal-jwt-keys, separate from jwt-keys:
#   kubectl create secret generic internal-jwt-keys \
#     --from-literal=INTERNAL_JWT_PRIVATE_KEY="$(cat internal_private.pem)" \
#     --from-literal=INTERNAL_JWT_PUBLIC_KEY="$(cat internal_public.pem)"
#   Mount INTERNAL_JWT_PRIVATE_KEY only into the Django Deployment.
#   Mount INTERNAL_JWT_PUBLIC_KEY into insights_service and ai_microservice Deployments.
#   The Django Deployment must never receive INTERNAL_JWT_PUBLIC_KEY of other services.
#
# KEY ROTATION — no coordination with the user JWT key pair required:
#   1. Generate a new internal key pair.
#   2. Deploy new INTERNAL_JWT_PUBLIC_KEY to all verifying services (both old and new trusted).
#   3. Update Django to sign with the new INTERNAL_JWT_PRIVATE_KEY.
#   4. Wait for all in-flight internal tokens to expire (INTERNAL_JWT_LIFETIME_SECONDS = 60s).
#   5. Remove the old public key from verifying services.
INTERNAL_JWT_PRIVATE_KEY = os.getenv('INTERNAL_JWT_PRIVATE_KEY', '').replace('\\n', '\n')
INTERNAL_JWT_PUBLIC_KEY = os.getenv('INTERNAL_JWT_PUBLIC_KEY', '').replace('\\n', '\n')
INTERNAL_JWT_ISSUER = os.getenv('INTERNAL_JWT_ISSUER', 'django-api')
INTERNAL_JWT_LIFETIME_SECONDS = 60  # seconds; intentionally short — internal hop only

MIDDLEWARE = [
    "silk.middleware.SilkyMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "MindedHealth.middleware.LogoutOnServerStartMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "MindedHealth.urls"
ASGI_APPLICATION = "MindedHealth.asgi.application"
WSGI_APPLICATION = "MindedHealth.wsgi.application"

# =======================
# TEMPLATES
# =======================
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# =======================
# DATABASE
# =======================
if DEBUG:
    # Local development uses SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / "db.sqlite3",
        }
    }
else:
    # Production (EKS) uses RDS PostgreSQL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'mindedhealth'),
            'USER': os.getenv('DB_USER', 'mindedhealth_user'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# =======================
# PASSWORD VALIDATION
# =======================
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# =======================
# SESSIONS
# =======================
SESSION_COOKIE_AGE = 60*60
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_SAVE_EVERY_REQUEST = True
SESSION_CACHE_ALIAS = "default"

# =======================
# REDIS & CELERY
# =======================
REDIS_HOST = os.getenv('REDIS_HOST', 'localhost')
REDIS_PORT = 6379
REDIS_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/0'

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(REDIS_HOST, REDIS_PORT)],
        },
    },
}

CELERY_BROKER_URL = REDIS_URL
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
    }
}

# =======================
# LOGGING
# =======================
LOGGING = {
    'version': 1,
    'handlers': {'console': {'class': 'logging.StreamHandler'}},
    'root': {'handlers': ['console'], 'level': "DEBUG" if DEBUG else "INFO"},
}
