# Generated by Django 5.2.4 on 2025-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('times_per_day', models.PositiveIntegerField()),
                ('dose', models.CharField(max_length=255)),
                ('dose_times', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_taken', models.TimeField()),
                ('dose_index', models.IntegerField()),
            ],
        ),
    ]
