# Generated by Django 5.1.1 on 2026-01-18 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medications', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicationLog',
        ),
    ]
