# Generated by Django 4.2.15 on 2025-05-29 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medications", "0006_medication_dose_times_medicationlog_delete_timetaken"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="medicationlog",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="medicationlog",
            name="dose_index",
            field=models.IntegerField(),
        ),
    ]
