# Generated by Django 5.1.1 on 2026-08-03 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PseudonymAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100)),
                ('chat_day', models.DateField()),
                ('pseudonym', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'room_name', 'chat_day'), name='uniq_pseudonym_per_user_room_day'), models.UniqueConstraint(fields=('room_name', 'chat_day', 'pseudonym'), name='uniq_pseudonym_per_room_day')],
            },
        ),
    ]
