# Generated by Django 5.2.4 on 2025-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeltOffLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('had_moment', models.BooleanField(default=False)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('intensity', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('breakfast_ate', models.BooleanField(blank=True, default=False, null=True)),
                ('breakfast_time', models.TimeField(blank=True, null=True)),
                ('lunch_ate', models.BooleanField(blank=True, default=False, null=True)),
                ('lunch_time', models.TimeField(blank=True, null=True)),
                ('dinner_ate', models.BooleanField(blank=True, default=False, null=True)),
                ('dinner_time', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('met_people', models.BooleanField(blank=True, default=False, null=True)),
                ('positivity_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=1)),
                ('meeting_type', models.CharField(blank=True, choices=[('family', 'With Family'), ('friends', 'With Friends'), ('business', 'Business Meeting'), ('strangers', 'With Strangers')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeizureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SleepingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('went_to_sleep_yesterday', models.TimeField(blank=True, null=True)),
                ('wake_up_time', models.TimeField(blank=True, null=True)),
                ('woke_up_during_night', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('did_sport', models.BooleanField(default=False)),
                ('sport_type', models.CharField(blank=True, choices=[('swimming', 'Swimming'), ('running', 'Running'), ('walking', 'Walking'), ('gym', 'Gym Session'), ('other', 'Other')], max_length=10, null=True)),
                ('other_sport', models.CharField(blank=True, max_length=100, null=True)),
                ('sport_time', models.TimeField(blank=True, default='00:00:00', null=True)),
            ],
        ),
    ]
