# Generated by Django 5.0.6 on 2024-07-05 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportlog",
            name="sport_time",
            field=models.TimeField(default="00:00:00"),
        ),
    ]
