# Generated by Django 5.0.6 on 2024-10-20 15:48

import dashboard.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_remove_seizurelog_last_memory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sleepinglog",
            old_name="wake_time",
            new_name="wake_up_time",
        ),
        migrations.AddField(
            model_name="sleepinglog",
            name="sleep_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="sleepinglog",
            name="wake_up_date",
            field=models.DateField(default=dashboard.models.get_tomorrow_date),
        ),
    ]
