# Generated by Django 5.1.1 on 2026-01-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_medicationintakelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicationintakelog',
            name='medication_ref_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
