# Generated by Django 5.1.1 on 2026-01-18 14:58

from django.db import migrations
from django.db.models import F


def backfill(apps, schema_editor):
    MedicationIntakeLog = apps.get_model("dashboard", "MedicationIntakeLog")
    MedicationIntakeLog.objects.filter(medication_ref_id__isnull=True).update(
        medication_ref_id=F("medication_id")
    )

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_medicationintakelog_medication_ref_id'),
    ]

    operations = [
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]