# Generated by Django 5.1.1 on 2026-01-18 15:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_backfill_medication_ref_id'),
        ('medications', '0003_delete_medicationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='medicationintakelog',
            name='uniq_med_intake_per_dose_per_day',
        ),
        migrations.AddConstraint(
            model_name='medicationintakelog',
            constraint=models.UniqueConstraint(fields=('user', 'medication_ref_id', 'date', 'dose_index'), name='uniq_med_intake_per_dose_per_day'),
        ),
    ]
