# Generated by Django 5.0.6 on 2024-10-20 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_remove_sleepinglog_sleep_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sleepinglog",
            old_name="wake_up_time",
            new_name="wake_time",
        ),
    ]
