# Generated by Django 5.1.1 on 2026-01-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_medicationintakelog_uniq_med_intake_per_dose_per_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicationintakelog',
            name='medication',
        ),
        migrations.AlterField(
            model_name='medicationintakelog',
            name='medication_ref_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
