# Generated by Django 5.0.6 on 2024-10-25 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_sleepinglog_sleep_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sleepinglog',
            unique_together=set(),
        ),
    ]
