# Generated by Django 5.0.6 on 2024-10-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_sleepinglog_sleep_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sleepinglog',
            name='wake_time',
        ),
        migrations.RemoveField(
            model_name='sleepinglog',
            name='woke_up_during_night',
        ),
        migrations.AddField(
            model_name='sleepinglog',
            name='wake_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sleepinglog',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='sleepinglog',
            name='sleep_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
