# Generated by Django 5.0.6 on 2024-10-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_sleepinglog_wake_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepinglog',
            name='woke_up_during_night',
            field=models.BooleanField(default=False),
        ),
    ]
