# Generated by Django 4.2.15 on 2025-07-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_went_to_sleep_time_sleepinglog_went_to_sleep_yesterday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodlog',
            name='breakfast_ate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='dinner_ate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='foodlog',
            name='lunch_ate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='sportlog',
            name='sport_time',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
