# Generated by Django 4.2.15 on 2025-07-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_foodlog_breakfast_ate_alter_foodlog_dinner_ate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='met_people',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
