apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-master-0
  namespace: redis
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  
  hostPath:
    path: /mnt/data/redis-master  
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-data-redis-replicas-0
  namespace: redis
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  
  hostPath:
    path: /mnt/data/redis-replicas  
