apiVersion: v1
kind: Service
metadata:
  name: mindedhealth-service
spec:
  selector:
    app: mindedhealth
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 8000  
  type: LoadBalancer  
